/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2022-11-30 14:17:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class LeftAdmin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/F:/Java/java-workspaces/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WebsiteBookStore/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1668259456904L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Sidebar -->\r\n");
      out.write("<nav id=\"sidebar\" class=\"sidebar js-sidebar\">\r\n");
      out.write("\t<div class=\"sidebar-content js-simplebar\">\r\n");
      out.write("\t\t<a class=\"sidebar-brand\" href=\"statictis.html\"> <span\r\n");
      out.write("\t\t\tclass=\"align-middle\">EShop Admin</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t<ul class=\"sidebar-nav\">\r\n");
      out.write("\t\t\t<li class=\"sidebar-item\"><a class=\"sidebar-link\"\r\n");
      out.write("\t\t\t\thref=\"admin\"> <i class=\"align-middle\"\r\n");
      out.write("\t\t\t\t\tdata-feather=\"sliders\"></i> <span class=\"align-middle\">Main\r\n");
      out.write("\t\t\t\t\t\tDashboard</span>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li class=\"sidebar-item\"><a class=\"sidebar-link\"\r\n");
      out.write("\t\t\t\thref=\"doanhThuTheoThu\"> <i class=\"align-middle\"\r\n");
      out.write("\t\t\t\t\tdata-feather=\"map\"></i> <span class=\"align-middle\">Doanh Thu\r\n");
      out.write("\t\t\t\t\t\tTheo Thứ</span>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li class=\"sidebar-item\"><a class=\"sidebar-link\" href=\"doanhThuTheoThang\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"align-middle\" data-feather=\"bar-chart-2\"></i> <span\r\n");
      out.write("\t\t\t\t\tclass=\"align-middle\">Doanh Thu Theo Tháng</span>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li class=\"sidebar-item\"><a class=\"sidebar-link\" href=\"hoaDon\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"align-middle\" data-feather=\"grid\"></i> <span\r\n");
      out.write("\t\t\t\t\tclass=\"align-middle\">Hóa Đơn</span>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li class=\"sidebar-item\"><a class=\"sidebar-link\" href=\"managerAccount\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"align-middle\" data-feather=\"user-plus\"></i> <span\r\n");
      out.write("\t\t\t\t\tclass=\"align-middle\">Quản lý tài khoản</span>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li class=\"sidebar-item\"><a class=\"sidebar-link\" href=\"manager\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"align-middle\" data-feather=\"square\"></i> <span\r\n");
      out.write("\t\t\t\t\tclass=\"align-middle\">Quản lý sản phẩm</span>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li class=\"sidebar-item\"><a class=\"sidebar-link\" href=\"top10\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"align-middle\" data-feather=\"coffee\"></i> <span\r\n");
      out.write("\t\t\t\t\tclass=\"align-middle\">Top 10 sản phẩm</span>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li class=\"sidebar-item\"><a class=\"sidebar-link\" href=\"top5khachhang\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"align-middle\" data-feather=\"user\"></i> <span\r\n");
      out.write("\t\t\t\t\tclass=\"align-middle\">Top 5 khách hàng</span>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li class=\"sidebar-item\"><a class=\"sidebar-link\" href=\"top5nhanvien\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"align-middle\" data-feather=\"user\"></i> <span\r\n");
      out.write("\t\t\t\t\tclass=\"align-middle\">Top 5 nhân viên</span>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li class=\"sidebar-item\"><a class=\"sidebar-link\" href=\"managerSupplier\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"align-middle\" data-feather=\"align-left\"></i> <span\r\n");
      out.write("\t\t\t\t\tclass=\"align-middle\">Quản lý nhà cung cấp</span>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</nav>\r\n");
      out.write("<!-- Sidebar -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
