/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2022-11-22 12:34:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Shop_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/F:/Java/java-workspaces/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WebsiteBookStore/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1668259456904L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("<title>Shop</title>\r\n");
      out.write("<!-- Favicon -->\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"images/favicon.png\">\r\n");
      out.write("<!-- Web Font -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Poppins:200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"fonts/icomoon/style.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Style -->\r\n");
      out.write("<link href=\"css/login.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("<!-- StyleSheet -->\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.css\">\r\n");
      out.write("<!-- Magnific Popup -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/magnific-popup.min.css\">\r\n");
      out.write("<!-- Font Awesome -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/font-awesome.css\">\r\n");
      out.write("<!-- Fancybox -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/jquery.fancybox.min.css\">\r\n");
      out.write("<!-- Themify Icons -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/themify-icons.css\">\r\n");
      out.write("<!-- Nice Select CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/niceselect.css\">\r\n");
      out.write("<!-- Animate CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/animate.css\">\r\n");
      out.write("<!-- Flex Slider CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/flex-slider.min.css\">\r\n");
      out.write("<!-- Owl Carousel -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/owl-carousel.css\">\r\n");
      out.write("<!-- Slicknav -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/slicknav.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Eshop StyleSheet -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/reset.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/responsive.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"js\" onload=\"loadAmountCart()\">\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Menu.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Product Style -->\r\n");
      out.write("\t<section class=\"product-area shop-sidebar shop section\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 col-md-4 col-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"shop-sidebar\">\r\n");
      out.write("\t\t\t\t\t\t<!-- Single Widget -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"single-widget category\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"title\">Categories</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"categor-list\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!--/ End Single Widget -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Shop by filter -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"single-widget category\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"ti-search\"></i> Filters\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Search Form -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-group flex-nowrap\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<input oninput=\"searchByName(this)\" name=\"txt\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${txtS}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"text\" class=\"form-control\" placeholder=\"Search...\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\taria-label=\"Username\" aria-describedby=\"addon-wrapping\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!--/ End Search Form -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!--/Shop by filter -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Shop By Price -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"single-widget range\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"title\">Shop by Price</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"price-filter\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"price-filter-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"input-group mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input oninput=\"searchByPriceMinToMax()\" id=\"priceMin\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" class=\"form-control\" placeholder=\"Min\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfor=\"priceMin\"> <span class=\"input-group-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t- </span> <input oninput=\"searchByPriceMinToMax()\" id=\"priceMax\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" class=\"form-control\" placeholder=\"Max\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfor=\"priceMin\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"check-box-list\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><label class=\"checkbox-inline\" for=\"1\"><input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonchange=\"searchByPriceUnder100()\" name=\"news\" id=\"1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"checkbox\" for=\"under100\">Under - 100</label></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><label class=\"checkbox-inline\" for=\"2\"><input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonchange=\"searchByPrice100To200()\" name=\"news\" id=\"2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"checkbox\" for=\"100200\">100 - 200</label></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><label class=\"checkbox-inline\" for=\"3\"><input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonchange=\"searchByPriceAbove200()\" name=\"news\" id=\"3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"checkbox\" for=\"200above\">200 - Above</label></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!--/ End Shop By Price -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-9 col-md-8 col-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Shop Top -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"shop-top\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"shop-shorter\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"single-shorter\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"view-mode\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"active\"><a href=\"shop-grid.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-th-large\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"shop-list.html\"><i class=\"fa fa-th-list\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!--/ End Shop Top -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\" id=\"content\">\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"pagination p1\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!--/ End Product Style 1  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction load(cateid){\r\n");
      out.write("\t\t\t $.ajax({\r\n");
      out.write("\t\t        url: \"/WebsiteBookStore/categoryShop\",\r\n");
      out.write("\t\t        type: \"get\", //send it through get method\r\n");
      out.write("\t\t        data: {\r\n");
      out.write("\t\t            cid: cateid\r\n");
      out.write("\t\t        },\r\n");
      out.write("\t\t        success: function (responseData) {\r\n");
      out.write("\t\t            document.getElementById(\"content\").innerHTML = responseData;\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t}  \r\n");
      out.write("\t\tfunction searchByName(param){\r\n");
      out.write("\t\t   var txtSearch = param.value;\r\n");
      out.write("\t\t   $.ajax({\r\n");
      out.write("\t\t       url: \"/WebsiteBookStore/searchAjaxShop\",\r\n");
      out.write("\t\t       type: \"get\", //send it through get method\r\n");
      out.write("\t\t       data: {\r\n");
      out.write("\t\t           txt: txtSearch\r\n");
      out.write("\t\t       },\r\n");
      out.write("\t\t       success: function (data) {\r\n");
      out.write("\t\t           var row = document.getElementById(\"content\");\r\n");
      out.write("\t\t           row.innerHTML = data;\r\n");
      out.write("\t\t       },\r\n");
      out.write("\t\t       error: function (xhr) {\r\n");
      out.write("\t\t           //Do Something to handle error\r\n");
      out.write("\t\t       }\r\n");
      out.write("\t\t   });\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction searchByPriceMinToMax(){\r\n");
      out.write("\t\t   var numMin = document.getElementById(\"priceMin\").value;\r\n");
      out.write("\t\t   var numMax = document.getElementById(\"priceMax\").value;\r\n");
      out.write("\t\t   $.ajax({\r\n");
      out.write("\t\t       url: \"/WebsiteBookStore/searchAjaxPriceMinToMax\",\r\n");
      out.write("\t\t       type: \"get\", //send it through get method\r\n");
      out.write("\t\t       data: {\r\n");
      out.write("\t\t           priceMin: numMin,\r\n");
      out.write("\t\t           priceMax: numMax\r\n");
      out.write("\t\t       },\r\n");
      out.write("\t\t       success: function (data) {\r\n");
      out.write("\t\t           var row = document.getElementById(\"content\");\r\n");
      out.write("\t\t           row.innerHTML = data;\r\n");
      out.write("\t\t       },\r\n");
      out.write("\t\t       error: function (xhr) {\r\n");
      out.write("\t\t           //Do Something to handle error\r\n");
      out.write("\t\t       }\r\n");
      out.write("\t\t   });\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction searchByPriceUnder100(){\r\n");
      out.write("\t\t   $.ajax({\r\n");
      out.write("\t\t       url: \"/WebsiteBookStore/searchAjaxPriceUnder100Shop\",\r\n");
      out.write("\t\t       type: \"get\", //send it through get method\r\n");
      out.write("\t\t       data: {\r\n");
      out.write("\t\t          \r\n");
      out.write("\t\t       },\r\n");
      out.write("\t\t       success: function (data) {\r\n");
      out.write("\t\t           var row = document.getElementById(\"content\");\r\n");
      out.write("\t\t           row.innerHTML = data;\r\n");
      out.write("\t\t       },\r\n");
      out.write("\t\t       error: function (xhr) {\r\n");
      out.write("\t\t           //Do Something to handle error\r\n");
      out.write("\t\t       }\r\n");
      out.write("\t\t   });\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction searchByPrice100To200(){\r\n");
      out.write("\t\t   $.ajax({\r\n");
      out.write("\t\t       url: \"/WebsiteBookStore/searchAjaxPrice100To200Shop\",\r\n");
      out.write("\t\t       type: \"get\", //send it through get method\r\n");
      out.write("\t\t       data: {\r\n");
      out.write("\t\t          \r\n");
      out.write("\t\t       },\r\n");
      out.write("\t\t       success: function (data) {\r\n");
      out.write("\t\t           var row = document.getElementById(\"content\");\r\n");
      out.write("\t\t           row.innerHTML = data;\r\n");
      out.write("\t\t       },\r\n");
      out.write("\t\t       error: function (xhr) {\r\n");
      out.write("\t\t           //Do Something to handle error\r\n");
      out.write("\t\t       }\r\n");
      out.write("\t\t   });\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction searchByPriceAbove200(){\r\n");
      out.write("\t\t   $.ajax({\r\n");
      out.write("\t\t       url: \"/WebsiteBookStore/searchAjaxPriceAbove200Shop\",\r\n");
      out.write("\t\t       type: \"get\", //send it through get method\r\n");
      out.write("\t\t       data: {\r\n");
      out.write("\t\t          \r\n");
      out.write("\t\t       },\r\n");
      out.write("\t\t       success: function (data) {\r\n");
      out.write("\t\t           var row = document.getElementById(\"content\");\r\n");
      out.write("\t\t           row.innerHTML = data;\r\n");
      out.write("\t\t       },\r\n");
      out.write("\t\t       error: function (xhr) {\r\n");
      out.write("\t\t           //Do Something to handle error\r\n");
      out.write("\t\t       }\r\n");
      out.write("\t\t   });\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction loadAmountCart(){\r\n");
      out.write("\t\t\t $.ajax({\r\n");
      out.write("\t\t        url: \"/WebsiteBookStore/loadAllAmountCart\",\r\n");
      out.write("\t\t        type: \"get\", //send it through get method\r\n");
      out.write("\t\t        data: {\r\n");
      out.write("\t\t            \r\n");
      out.write("\t\t        },\r\n");
      out.write("\t\t        success: function (responseData) {\r\n");
      out.write("\t\t            document.getElementById(\"amountCart\").innerHTML = responseData;\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t}      \r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Footer -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Jquery -->\r\n");
      out.write("\t<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery-migrate-3.0.0.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery-ui.min.js\"></script>\r\n");
      out.write("\t<!-- Popper JS -->\r\n");
      out.write("\t<script src=\"js/popper.min.js\"></script>\r\n");
      out.write("\t<!-- Bootstrap JS -->\r\n");
      out.write("\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<!-- Color JS -->\r\n");
      out.write("\t<script src=\"js/colors.js\"></script>\r\n");
      out.write("\t<!-- Slicknav JS -->\r\n");
      out.write("\t<script src=\"js/slicknav.min.js\"></script>\r\n");
      out.write("\t<!-- Owl Carousel JS -->\r\n");
      out.write("\t<script src=\"js/owl-carousel.js\"></script>\r\n");
      out.write("\t<!-- Magnific Popup JS -->\r\n");
      out.write("\t<script src=\"js/magnific-popup.js\"></script>\r\n");
      out.write("\t<!-- Fancybox JS -->\r\n");
      out.write("\t<script src=\"js/facnybox.min.js\"></script>\r\n");
      out.write("\t<!-- Waypoints JS -->\r\n");
      out.write("\t<script src=\"js/waypoints.min.js\"></script>\r\n");
      out.write("\t<!-- Countdown JS -->\r\n");
      out.write("\t<script src=\"js/finalcountdown.min.js\"></script>\r\n");
      out.write("\t<!-- Nice Select JS -->\r\n");
      out.write("\t<script src=\"js/nicesellect.js\"></script>\r\n");
      out.write("\t<!-- Ytplayer JS -->\r\n");
      out.write("\t<script src=\"js/ytplayer.min.js\"></script>\r\n");
      out.write("\t<!-- Flex Slider JS -->\r\n");
      out.write("\t<script src=\"js/flex-slider.js\"></script>\r\n");
      out.write("\t<!-- ScrollUp JS -->\r\n");
      out.write("\t<script src=\"js/scrollup.js\"></script>\r\n");
      out.write("\t<!-- Onepage Nav JS -->\r\n");
      out.write("\t<script src=\"js/onepage-nav.min.js\"></script>\r\n");
      out.write("\t<!-- Easing JS -->\r\n");
      out.write("\t<script src=\"js/easing.js\"></script>\r\n");
      out.write("\t<!-- Active JS -->\r\n");
      out.write("\t<script src=\"js/active.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /Shop.jsp(72,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/Shop.jsp(72,8) '${listCC}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${listCC}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /Shop.jsp(72,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("o");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<li><a onclick=\"load(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.cid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(')');
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.cname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></li>\r\n");
            out.write("\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /Shop.jsp(147,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/Shop.jsp(147,6) '${listP}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${listP}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /Shop.jsp(147,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("o");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t<!-- product -->\r\n");
            out.write("\t\t\t\t\t\t\t<div class=\"col-lg-4 col-md-6 col-12\">\r\n");
            out.write("\t\t\t\t\t\t\t\t<div class=\"single-product\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<div class=\"product-img\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"detail?pid=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"> <img class=\"default-img\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\tsrc=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.image }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" alt=\"#\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"button-head\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"product-action-2\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a title=\"Add to cart\" href=\"#\">Add to cart</a>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<div class=\"product-content\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<h3>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"detail?pid=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</h3>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product-price\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("$</span>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t<!-- product -->\r\n");
            out.write("\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /Shop.jsp(178,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tag != 1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<a href=\"shop?index=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tag-1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"><li><</li></a>\r\n");
          out.write("\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /Shop.jsp(182,8) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setBegin(1);
      // /Shop.jsp(182,8) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setEnd(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${endPage }", int.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).intValue());
      // /Shop.jsp(182,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("i");
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<a class=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tag==i?\" is-active\":\"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" href=\"shop?index=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"><li>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</li></a>\r\n");
            out.write("\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /Shop.jsp(186,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tag != endPage}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<a href=\"shop?index=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tag+1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"><li>></li></a>\r\n");
          out.write("\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
