/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2022-11-15 13:23:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class DetailProduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/F:/Java/java-workspaces/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WebsiteBookStore/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1668259456904L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("      <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("  <title>Detail Product</title>\r\n");
      out.write("  <!-- Roboto Font -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700&display=swap\">\r\n");
      out.write("  <!-- Font Awesome -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.11.2/css/all.css\">\r\n");
      out.write("  <!-- Bootstrap core CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://mdbootstrap.com/previews/ecommerce-demo/css/bootstrap.min.css\">\r\n");
      out.write("  <!-- Material Design Bootstrap -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://mdbootstrap.com/previews/ecommerce-demo/css/mdb-pro.min.css\">\r\n");
      out.write("  <!-- Material Design Bootstrap Ecommerce -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://mdbootstrap.com/previews/ecommerce-demo/css/mdb.ecommerce.min.css\">\r\n");
      out.write("  <!-- Your custom styles (optional) -->\r\n");
      out.write("\t\r\n");
      out.write("\t  <link href=\"//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("        <script src=\"//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("        <script src=\"//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("        <link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("        \r\n");
      out.write("         <style>\r\n");
      out.write("            .gallery-wrap .img-big-wrap img {\r\n");
      out.write("                height: 450px;\r\n");
      out.write("                width: auto;\r\n");
      out.write("                display: inline-block;\r\n");
      out.write("                cursor: zoom-in;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            .gallery-wrap .img-small-wrap .item-gallery {\r\n");
      out.write("                width: 60px;\r\n");
      out.write("                height: 60px;\r\n");
      out.write("                border: 1px solid #ddd;\r\n");
      out.write("                margin: 7px 2px;\r\n");
      out.write("                display: inline-block;\r\n");
      out.write("                overflow: hidden;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .gallery-wrap .img-small-wrap {\r\n");
      out.write("                text-align: center;\r\n");
      out.write("            }\r\n");
      out.write("            .gallery-wrap .img-small-wrap img {\r\n");
      out.write("                max-width: 100%;\r\n");
      out.write("                max-height: 100%;\r\n");
      out.write("                object-fit: cover;\r\n");
      out.write("                border-radius: 4px;\r\n");
      out.write("                cursor: zoom-in;\r\n");
      out.write("            }\r\n");
      out.write("            .img-big-wrap img{\r\n");
      out.write("                width: 100% !important;\r\n");
      out.write("                height: auto !important;\r\n");
      out.write("            }\r\n");
      out.write("        </style>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body class=\"skin-light\">\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Menu.jsp", out, false);
      out.write("\r\n");
      out.write("        \r\n");
      out.write("      <div class=\"jumbotron color-grey-light mt-70\">\r\n");
      out.write("      <div class=\"d-flex align-items-center h-100\">\r\n");
      out.write("        <div class=\"container text-center py-5\">\r\n");
      out.write("          <h3 class=\"mb-0\"></h3>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!--Main Navigation-->\r\n");
      out.write("\r\n");
      out.write("  <!--Main layout-->\r\n");
      out.write("  <main>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("      <!--Section: Block Content-->\r\n");
      out.write("      <section class=\"mb-5\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-6 mb-4 mb-md-0\">\r\n");
      out.write("\r\n");
      out.write("            <div id=\"mdb-lightbox-ui\"></div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mdb-lightbox\">\r\n");
      out.write("\r\n");
      out.write("              <div class=\"row product-gallery mx-1\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 mb-0\">\r\n");
      out.write("                  <figure class=\"view overlay rounded z-depth-1 main-img\" style=\"max-height: 450px;\">\r\n");
      out.write("                    <a href=\"https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/15a.jpg\"\r\n");
      out.write("                      data-size=\"710x823\">\r\n");
      out.write("                      <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("                        class=\"img-fluid z-depth-1\" style=\"margin-top: -90px;\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </figure>\r\n");
      out.write("                  <figure class=\"view overlay rounded z-depth-1\" style=\"visibility: hidden;\">\r\n");
      out.write("                    <a href=\"https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12a.jpg\"\r\n");
      out.write("                      data-size=\"710x823\">\r\n");
      out.write("                      <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.image2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("                        class=\"img-fluid z-depth-1\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </figure>\r\n");
      out.write("                  <figure class=\"view overlay rounded z-depth-1\" style=\"visibility: hidden;\">\r\n");
      out.write("                    <a href=\"https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/13a.jpg\"\r\n");
      out.write("                      data-size=\"710x823\">\r\n");
      out.write("                      <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.image3}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("                        class=\"img-fluid z-depth-1\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </figure>\r\n");
      out.write("                  <figure class=\"view overlay rounded z-depth-1\" style=\"visibility: hidden;\">\r\n");
      out.write("                    <a href=\"https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/14a.jpg\"\r\n");
      out.write("                      data-size=\"710x823\">\r\n");
      out.write("                      <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.image4}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("                        class=\"img-fluid z-depth-1\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </figure>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-3\">\r\n");
      out.write("                      <div class=\"view overlay rounded z-depth-1 gallery-item hoverable\" >\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("                          class=\"img-fluid\">\r\n");
      out.write("                        <div class=\"mask rgba-white-slight\"></div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-3\">\r\n");
      out.write("                      <div class=\"view overlay rounded z-depth-1 gallery-item hoverable\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.image2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("                          class=\"img-fluid\">\r\n");
      out.write("                        <div class=\"mask rgba-white-slight\"></div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-3\">\r\n");
      out.write("                      <div class=\"view overlay rounded z-depth-1 gallery-item hoverable\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.image3}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" \r\n");
      out.write("                        class=\"img-fluid\">\r\n");
      out.write("                        <div class=\"mask rgba-white-slight\"></div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-3\">\r\n");
      out.write("                      <div class=\"view overlay rounded z-depth-1 gallery-item hoverable\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.image4}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" \r\n");
      out.write("                         class=\"img-fluid\">\r\n");
      out.write("                        <div class=\"mask rgba-white-slight\"></div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-6\">\r\n");
      out.write("\r\n");
      out.write("            <h5>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h5>\r\n");
      out.write("        \r\n");
      out.write("            <p><span class=\"mr-1\"><strong>$");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${String.format(\"%.02f\",detail.price*0.9) }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong></span><span\r\n");
      out.write("                    class=\"text-grey\"><strong><s>$");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</s></strong></span></p>\r\n");
      out.write("            \r\n");
      out.write("                    \r\n");
      out.write("            <p class=\"pt-1\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.description}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("            <div class=\"table-responsive\">\r\n");
      out.write("              <table class=\"table table-sm table-borderless mb-0\">\r\n");
      out.write("                <tbody>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <th class=\"pl-0 w-25\" scope=\"row\"><strong>Model</strong></th>\r\n");
      out.write("                    <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.model }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <th class=\"pl-0 w-25\" scope=\"row\"><strong>Color</strong></th>\r\n");
      out.write("                    <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.color }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <th class=\"pl-0 w-25\" scope=\"row\"><strong>Delivery</strong></th>\r\n");
      out.write("                    <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.delivery }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </tbody>\r\n");
      out.write("              </table>\r\n");
      out.write("            </div>\r\n");
      out.write("            <hr>\r\n");
      out.write("            \r\n");
      out.write("            <form action=\"addCart?pid=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" method=\"post\">\r\n");
      out.write("            <div class=\"table-responsive mb-2\">\r\n");
      out.write("              <table class=\"table table-sm table-borderless\">\r\n");
      out.write("                <tbody>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td class=\"pl-0 pb-0 w-25\">Quantity</td>\r\n");
      out.write("                    <td class=\"pb-0\">Select size</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td class=\"pl-0\">\r\n");
      out.write("                    <div class=\"mt-1\">\r\n");
      out.write("                      <div class=\"def-number-input number-input safari_only mb-0\" style=\"display: flex; align-items: center;\">\r\n");
      out.write("                        <button type=\"button\" onclick=\"this.parentNode.querySelector('input[type=number]').stepDown()\"\r\n");
      out.write("                          class=\"minus\"></button>\r\n");
      out.write("                        <input class=\"quantity\" min=\"0\" name=\"quantity\" value=\"1\" type=\"number\">\r\n");
      out.write("                        <button type=\"button\" onclick=\"this.parentNode.querySelector('input[type=number]').stepUp()\"\r\n");
      out.write("                          class=\"plus\"></button>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                      <div class=\"mt-1\">\r\n");
      out.write("                        <div class=\"form-check form-check-inline pl-0\">\r\n");
      out.write("                          <input type=\"radio\" class=\"form-check-input\" id=\"small\" value=\"small\" name=\"size\" checked>\r\n");
      out.write("                          <label class=\"form-check-label small text-uppercase card-link-secondary\"\r\n");
      out.write("                            for=\"small\">Small</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-check form-check-inline pl-0\">\r\n");
      out.write("                          <input type=\"radio\" class=\"form-check-input\" id=\"medium\" value=\"medium\" name=\"size\">\r\n");
      out.write("                          <label class=\"form-check-label small text-uppercase card-link-secondary\"\r\n");
      out.write("                            for=\"medium\">Medium</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-check form-check-inline pl-0\">\r\n");
      out.write("                          <input type=\"radio\" class=\"form-check-input\" id=\"large\" value=\"large\" name=\"size\">\r\n");
      out.write("                          <label class=\"form-check-label small text-uppercase card-link-secondary\"\r\n");
      out.write("                            for=\"large\">Large</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </tbody>\r\n");
      out.write("              </table>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"mt-1\">\r\n");
      out.write("             <button type=\"submit\" class=\"btn btn-primary btn-md mr-1 mb-2\">Buy now</button>\r\n");
      out.write("           <button type=\"submit\" class=\"btn btn-light btn-md mr-1 mb-2\"><i class=\"fas fa-shopping-cart pr-2\"></i>Add to\r\n");
      out.write("              cart</button>\r\n");
      out.write("              </div>\r\n");
      out.write("              </form>\r\n");
      out.write("              \r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </section>\r\n");
      out.write("      <!--Section: Block Content-->\r\n");
      out.write("\r\n");
      out.write("      <!-- Classic tabs -->\r\n");
      out.write("      <div class=\"classic-tabs\">\r\n");
      out.write("\r\n");
      out.write("        <ul class=\"nav tabs-primary nav-justified\" id=\"advancedTab\" role=\"tablist\">\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link active show\" id=\"description-tab\" data-toggle=\"tab\" href=\"#description\" role=\"tab\"\r\n");
      out.write("              aria-controls=\"description\" aria-selected=\"true\">Description</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" id=\"info-tab\" data-toggle=\"tab\" href=\"#info\" role=\"tab\" aria-controls=\"info\"\r\n");
      out.write("              aria-selected=\"false\">Information</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" id=\"reviews-tab\" data-toggle=\"tab\" href=\"#reviews\" role=\"tab\" aria-controls=\"reviews\"\r\n");
      out.write("              aria-selected=\"false\">Reviews (");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${countAllReview }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</a>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <div class=\"tab-content\" id=\"advancedTabContent\">\r\n");
      out.write("          <div class=\"tab-pane fade show active\" id=\"description\" role=\"tabpanel\" aria-labelledby=\"description-tab\">\r\n");
      out.write("            <h5>Product Description</h5>\r\n");
      out.write("            \r\n");
      out.write("            <h6>$");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${String.format(\"%.02f\",detail.price*0.9) }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h6>\r\n");
      out.write("            <p class=\"pt-1\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.description}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"tab-pane fade\" id=\"info\" role=\"tabpanel\" aria-labelledby=\"info-tab\">\r\n");
      out.write("            <h5>Additional Information</h5>\r\n");
      out.write("            <table class=\"table table-striped table-bordered mt-3\">\r\n");
      out.write("              <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <th scope=\"row\" class=\"w-150 dark-grey-text h6\">Weight</th>\r\n");
      out.write("                  <td><em>0.3 kg</em></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("              </thead>\r\n");
      out.write("              <tbody>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <th scope=\"row\" class=\"w-150 dark-grey-text h6\">Dimensions</th>\r\n");
      out.write("                  <td><em>50 × 60 cm</em></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("              </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"tab-pane fade\" id=\"reviews\" role=\"tabpanel\" aria-labelledby=\"reviews-tab\">\r\n");
      out.write("            <h5><span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${countAllReview }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span> review for <span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></h5>\r\n");
      out.write("            \r\n");
      out.write("             <h5 class=\"mt-4\">Add a review</h5>\r\n");
      out.write("            <p></p>\r\n");
      out.write("      \r\n");
      out.write("            <div>\r\n");
      out.write("              <!-- Your review -->\r\n");
      out.write("              <div class=\"md-form md-outline\">\r\n");
      out.write("                <textarea id=\"form76\" class=\"md-textarea form-control pr-6\" rows=\"4\"></textarea>\r\n");
      out.write("                <label for=\"form76\">Your review</label>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"text-right pb-2\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-primary\" onclick=\"addReview(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")\">Add a review</button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            \r\n");
      out.write("           \r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- Classic tabs -->\r\n");
      out.write("\r\n");
      out.write("      <hr>\r\n");
      out.write("\r\n");
      out.write("      <!--Section: Block Content-->\r\n");
      out.write("      <section class=\"text-center\">\r\n");
      out.write("\r\n");
      out.write("        <h4 class=\"text-center my-5\"><strong>Related products</strong></h4>\r\n");
      out.write("\r\n");
      out.write("        <!-- Grid row -->\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t \r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Grid row -->\r\n");
      out.write("\r\n");
      out.write("      </section>\r\n");
      out.write("      <!--Section: Block Content-->\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </main>\r\n");
      out.write("  <!--Main layout-->\r\n");
      out.write("  \r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("       ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.jsp", out, false);
      out.write("\r\n");
      out.write("       <script>\r\n");
      out.write("        window.addEventListener(\"load\",function loadAmountCart(){\r\n");
      out.write("                        \t $.ajax({\r\n");
      out.write("                                 url: \"/WebsiteBookStore/loadAllAmountCart\",\r\n");
      out.write("                                 type: \"get\", //send it through get method\r\n");
      out.write("                                 data: {\r\n");
      out.write("                                     \r\n");
      out.write("                                 },\r\n");
      out.write("                                 success: function (responseData) {\r\n");
      out.write("                                     document.getElementById(\"amountCart\").innerHTML = responseData;\r\n");
      out.write("                                 }\r\n");
      out.write("                             });\r\n");
      out.write("                        },false); \r\n");
      out.write("        \r\n");
      out.write("        function addReview(pID){\r\n");
      out.write("           var cntReview = document.getElementById(\"form76\").value;\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url: \"/WebsiteBookStore/addReview\",\r\n");
      out.write("                type: \"get\", //send it through get method\r\n");
      out.write("                data: {\r\n");
      out.write("                \tproductID: pID,\r\n");
      out.write("                \tcontentReview: cntReview\r\n");
      out.write("                },\r\n");
      out.write("                success: function (data) {\r\n");
      out.write("                    var row = document.getElementById(\"reviews\");\r\n");
      out.write("                    row.innerHTML += data;\r\n");
      out.write("                },\r\n");
      out.write("                error: function (xhr) {\r\n");
      out.write("                    //Do Something to handle error\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        </script>\r\n");
      out.write("        <!-- SCRIPTS -->\r\n");
      out.write("  <!-- JQuery -->\r\n");
      out.write("  <script src=\"../../../js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("  <!-- Bootstrap tooltips -->\r\n");
      out.write("  <script type=\"text/javascript\" src=\"https://mdbootstrap.com/previews/ecommerce-demo/js/popper.min.js\"></script>\r\n");
      out.write("  <!-- Bootstrap core JavaScript -->\r\n");
      out.write("  <script type=\"text/javascript\" src=\"https://mdbootstrap.com/previews/ecommerce-demo/js/bootstrap.js\"></script>\r\n");
      out.write("  <!-- MDB core JavaScript -->\r\n");
      out.write("  <script type=\"text/javascript\" src=\"https://mdbootstrap.com/previews/ecommerce-demo/js/mdb.min.js\"></script>\r\n");
      out.write("    <!-- MDB Ecommerce JavaScript -->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://mdbootstrap.com/previews/ecommerce-demo/js/mdb.ecommerce.min.js\"></script>\r\n");
      out.write("  <script>\r\n");
      out.write("    $(document).ready(function () {\r\n");
      out.write("      // MDB Lightbox Init\r\n");
      out.write("      $(function () {\r\n");
      out.write("        $(\"#mdb-lightbox-ui\").load(\"../../../mdb-addons/mdb-lightbox-ui.html\");\r\n");
      out.write("      });\r\n");
      out.write("    });\r\n");
      out.write("  </script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /DetailProduct.jsp(304,12) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/DetailProduct.jsp(304,12) '${listAllReview}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${listAllReview}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /DetailProduct.jsp(304,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("r");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("            \r\n");
            out.write("             <div class=\"media mt-3 mb-4\">\r\n");
            out.write("              <img class=\"d-flex mr-3 z-depth-1\" src=\"https://mdbootstrap.com/img/Photos/Others/placeholder1.jpg\"\r\n");
            out.write("                width=\"62\" alt=\"Generic placeholder image\">\r\n");
            out.write("              <div class=\"media-body\">\r\n");
            out.write("                <div class=\"d-flex justify-content-between\">\r\n");
            out.write("                  <p class=\"mt-1 mb-2\">\r\n");
            out.write("                  ");
            if (_jspx_meth_c_005fforEach_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("                    <span>– </span><span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${r.dateReview }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("                  </p>\r\n");
            out.write("                </div>\r\n");
            out.write("                <p class=\"mb-0\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${r.contentReview }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("              </div>\r\n");
            out.write("            </div>\r\n");
            out.write("            <hr>    \r\n");
            out.write("                 \r\n");
            out.write(" \t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /DetailProduct.jsp(312,18) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/DetailProduct.jsp(312,18) '${listAllAcount}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${listAllAcount}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /DetailProduct.jsp(312,18) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("a");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                  ");
            if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("\r\n");
            out.write("                     ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /DetailProduct.jsp(313,18) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${r.accountID == a.id }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                    <strong>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.user }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" </strong>\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /DetailProduct.jsp(347,1) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/DetailProduct.jsp(347,1) '${listRelatedProduct}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${listRelatedProduct}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /DetailProduct.jsp(347,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("o");
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("          <!-- Grid column -->\r\n");
            out.write("          <div class=\"col-md-6 col-lg-3 mb-5\">\r\n");
            out.write("\r\n");
            out.write("            <!-- Card -->\r\n");
            out.write("            <div class=\"\">\r\n");
            out.write("\r\n");
            out.write("              <div class=\"view zoom overlay z-depth-2 rounded\">\r\n");
            out.write("                <img class=\"img-fluid w-100\"\r\n");
            out.write("                  src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.image }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" alt=\"Sample\">\r\n");
            out.write("                  <h4 class=\"mb-0\"><span class=\"badge badge-primary badge-pill badge-news\">Sale 10%</span></h4>\r\n");
            out.write("                <a href=\"detail?pid=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                  <div class=\"mask\">\r\n");
            out.write("                    <img class=\"img-fluid w-100\"\r\n");
            out.write("                      src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.image }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                    <div class=\"mask rgba-black-slight\"></div>\r\n");
            out.write("                  </div>\r\n");
            out.write("                </a>\r\n");
            out.write("              </div>\r\n");
            out.write("\r\n");
            out.write("              <div class=\"pt-4\">\r\n");
            out.write("\r\n");
            out.write("                <h5>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h5>\r\n");
            out.write("                <p><span class=\"text-danger mr-1\"><strong>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${String.format(\"%.02f\",o.price*0.9) }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("$</strong></span><span\r\n");
            out.write("                    class=\"text-grey\"><strong><s>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("$</s></strong></span></p>\r\n");
            out.write("                    \r\n");
            out.write("               \r\n");
            out.write("\r\n");
            out.write("              </div>\r\n");
            out.write("\r\n");
            out.write("            </div>\r\n");
            out.write("            <!-- Card -->\r\n");
            out.write("\r\n");
            out.write("          </div>\r\n");
            out.write("          <!-- Grid column -->\r\n");
            out.write("\t ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }
}
