/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2022-11-15 13:15:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!-- Start Shop Services Area -->\n");
      out.write("<section id=\"service\" class=\"shop-services section home\">\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t<div class=\"col-lg-3 col-md-6 col-12\">\n");
      out.write("\t\t\t\t<!-- Start Single Service -->\n");
      out.write("\t\t\t\t<div class=\"single-service\">\n");
      out.write("\t\t\t\t\t<i class=\"ti-rocket\"></i>\n");
      out.write("\t\t\t\t\t<h4>Free shiping</h4>\n");
      out.write("\t\t\t\t\t<p>Orders over $100</p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!-- End Single Service -->\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"col-lg-3 col-md-6 col-12\">\n");
      out.write("\t\t\t\t<!-- Start Single Service -->\n");
      out.write("\t\t\t\t<div class=\"single-service\">\n");
      out.write("\t\t\t\t\t<i class=\"ti-reload\"></i>\n");
      out.write("\t\t\t\t\t<h4>Free Return</h4>\n");
      out.write("\t\t\t\t\t<p>Within 30 days returns</p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!-- End Single Service -->\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"col-lg-3 col-md-6 col-12\">\n");
      out.write("\t\t\t\t<!-- Start Single Service -->\n");
      out.write("\t\t\t\t<div class=\"single-service\">\n");
      out.write("\t\t\t\t\t<i class=\"ti-lock\"></i>\n");
      out.write("\t\t\t\t\t<h4>Sucure Payment</h4>\n");
      out.write("\t\t\t\t\t<p>100% secure payment</p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!-- End Single Service -->\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"col-lg-3 col-md-6 col-12\">\n");
      out.write("\t\t\t\t<!-- Start Single Service -->\n");
      out.write("\t\t\t\t<div class=\"single-service\">\n");
      out.write("\t\t\t\t\t<i class=\"ti-tag\"></i>\n");
      out.write("\t\t\t\t\t<h4>Best Peice</h4>\n");
      out.write("\t\t\t\t\t<p>Guaranteed price</p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!-- End Single Service -->\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</section>\n");
      out.write("<!-- End Shop Services Area -->\n");
      out.write("\n");
      out.write("<!-- Start Shop Newsletter  -->\n");
      out.write("<section class=\"shop-newsletter section\">\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t\t<div class=\"inner-top\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-lg-8 offset-lg-2 col-12\">\n");
      out.write("\t\t\t\t\t<!-- Start Newsletter Inner -->\n");
      out.write("\t\t\t\t\t<div class=\"inner\">\n");
      out.write("\t\t\t\t\t\t<h4>Newsletter</h4>\n");
      out.write("\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\tSubscribe to our newsletter and get <span>10%</span> off your\n");
      out.write("\t\t\t\t\t\t\tfirst purchase\n");
      out.write("\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t<form action=\"mail/mail.php\" method=\"get\" target=\"_blank\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"newsletter-inner\">\n");
      out.write("\t\t\t\t\t\t\t<input name=\"EMAIL\" placeholder=\"Your email address\" required=\"\"\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"email\">\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn\">Subscribe</button>\n");
      out.write("\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- End Newsletter Inner -->\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</section>\n");
      out.write("<!-- End Shop Newsletter -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Start Footer Area -->\n");
      out.write("<footer class=\"footer\">\n");
      out.write("\t<!-- Footer Top -->\n");
      out.write("\t<div class=\"footer-top section\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-lg-5 col-md-6 col-12\">\n");
      out.write("\t\t\t\t\t<!-- Single Widget -->\n");
      out.write("\t\t\t\t\t<div class=\"single-footer about\">\n");
      out.write("\t\t\t\t\t\t<div class=\"logo\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"index.html\"><img src=\"images/logo2.png\" alt=\"#\"></a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<p class=\"text\">Very happy to serve you</p>\n");
      out.write("\t\t\t\t\t\t<p class=\"call\">\n");
      out.write("\t\t\t\t\t\t\tGot Question? Call us 24/7<span><a href=\"tel:123456789\">+0123\n");
      out.write("\t\t\t\t\t\t\t\t\t456 789</a></span>\n");
      out.write("\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- End Single Widget -->\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-lg-2 col-md-6 col-12\">\n");
      out.write("\t\t\t\t\t<!-- Single Widget -->\n");
      out.write("\t\t\t\t\t<div class=\"single-footer links\">\n");
      out.write("\t\t\t\t\t\t<h4>Information</h4>\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">About Us</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Faq</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Terms & Conditions</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Contact Us</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Help</a></li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- End Single Widget -->\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-lg-2 col-md-6 col-12\">\n");
      out.write("\t\t\t\t\t<!-- Single Widget -->\n");
      out.write("\t\t\t\t\t<div class=\"single-footer links\">\n");
      out.write("\t\t\t\t\t\t<h4>Customer Service</h4>\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Payment Methods</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Money-back</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Returns</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Shipping</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Privacy Policy</a></li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- End Single Widget -->\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 col-md-6 col-12\">\n");
      out.write("\t\t\t\t\t<!-- Single Widget -->\n");
      out.write("\t\t\t\t\t<div class=\"single-footer social\">\n");
      out.write("\t\t\t\t\t\t<h4>Get In Tuch</h4>\n");
      out.write("\t\t\t\t\t\t<!-- Single Widget -->\n");
      out.write("\t\t\t\t\t\t<div class=\"contact\">\n");
      out.write("\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t<li>470 Đường Trần Đại Nghĩa, Khu đô thị, Ngũ Hành Sơn, Đà\n");
      out.write("\t\t\t\t\t\t\t\t\tNẵng 550000</li>\n");
      out.write("\t\t\t\t\t\t\t\t<li>TRƯỜNG ĐH CNTT VÀ TT VIỆT HÀN</li>\n");
      out.write("\t\t\t\t\t\t\t\t<li>ebookstore.final@gmail.com</li>\n");
      out.write("\t\t\t\t\t\t\t\t<li>+0123 456 789</li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<!-- End Single Widget -->\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"ti-facebook\"></i></a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"ti-twitter\"></i></a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"ti-flickr\"></i></a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"ti-instagram\"></i></a></li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- End Single Widget -->\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- End Footer Top -->\n");
      out.write("\t<div class=\"copyright\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"inner\">\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-6 col-12\">\n");
      out.write("\t\t\t\t\t\t<div class=\"left\">\n");
      out.write("\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\tCopyright © 2020 <a href=\"http://www.wpthemesgrid.com\"\n");
      out.write("\t\t\t\t\t\t\t\t\ttarget=\"_blank\">Wpthemesgrid</a> - All Rights Reserved.\n");
      out.write("\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-6 col-12\">\n");
      out.write("\t\t\t\t\t\t<div class=\"right\">\n");
      out.write("\t\t\t\t\t\t\t<img src=\"images/payments.png\" alt=\"#\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</footer>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
