/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2022-11-15 15:32:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/F:/Java/java-workspaces/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WebsiteBookStore/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1668259456904L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Home Page</title>\n");
      out.write("\n");
      out.write("<!-- Favicon -->\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"images/favicon.png\">\n");
      out.write("<!-- Web Font -->\n");
      out.write("<link\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Poppins:200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- StyleSheet -->\n");
      out.write("\n");
      out.write("<!-- Bootstrap -->\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.css\">\n");
      out.write("<!-- Magnific Popup -->\n");
      out.write("<link rel=\"stylesheet\" href=\"css/magnific-popup.min.css\">\n");
      out.write("<!-- Font Awesome -->\n");
      out.write("<link rel=\"stylesheet\" href=\"css/font-awesome.css\">\n");
      out.write("<!-- Fancybox -->\n");
      out.write("<link rel=\"stylesheet\" href=\"css/jquery.fancybox.min.css\">\n");
      out.write("<!-- Themify Icons -->\n");
      out.write("<link rel=\"stylesheet\" href=\"css/themify-icons.css\">\n");
      out.write("<!-- Nice Select CSS -->\n");
      out.write("<link rel=\"stylesheet\" href=\"css/niceselect.css\">\n");
      out.write("<!-- Animate CSS -->\n");
      out.write("<link rel=\"stylesheet\" href=\"css/animate.css\">\n");
      out.write("<!-- Flex Slider CSS -->\n");
      out.write("<link rel=\"stylesheet\" href=\"css/flex-slider.min.css\">\n");
      out.write("<!-- Owl Carousel -->\n");
      out.write("<link rel=\"stylesheet\" href=\"css/owl-carousel.css\">\n");
      out.write("<!-- Slicknav -->\n");
      out.write("<link rel=\"stylesheet\" href=\"css/slicknav.min.css\">\n");
      out.write("\n");
      out.write("<!-- Eshop StyleSheet -->\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"css/reset.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/responsive.css\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body class=\"js\t\" onload=\"loadAmountCart()\">\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Menu.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("\t<!-- New Book -->\n");
      out.write("\t<div id=\"newbooks\" class=\"product-area most-popular section\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-12\">\n");
      out.write("\t\t\t\t\t<div class=\"section-title\">\n");
      out.write("\t\t\t\t\t\t<h2>Recent Products</h2>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-12\">\n");
      out.write("\t\t\t\t\t<div class=\"owl-carousel popular-slider\">\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- End New Book -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<!-- Novel Latest -->\n");
      out.write("\t<div class=\"product-area section\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-12\">\n");
      out.write("\t\t\t\t\t<div class=\"section-title\">\n");
      out.write("\t\t\t\t\t\t<h2>Latest novels</h2>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-12\">\n");
      out.write("\t\t\t\t\t<div class=\"product-info\">\n");
      out.write("\t\t\t\t\t\t<div class=\"tab-content\" id=\"myTabContent\">\n");
      out.write("\t\t\t\t\t\t\t<!-- Start Single Tab -->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tab-pane fade show active\" id=\"man\" role=\"tabpanel\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tab-single\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"contentNovel\" class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<!--/ End Single Tab -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<button onclick=\"loadMoreNovel()\" class=\"btn btn-primary btn-lg\"\n");
      out.write("\t\t\tstyle=\"margin: 40px auto; display: flex;\">Load More</button>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- End Novel Latest -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<!-- Comic Lastest -->\n");
      out.write("\t<div class=\"product-area section\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-12\">\n");
      out.write("\t\t\t\t\t<div class=\"section-title\">\n");
      out.write("\t\t\t\t\t\t<h2>Latest Comics</h2>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-12\">\n");
      out.write("\t\t\t\t\t<div class=\"product-info\">\n");
      out.write("\t\t\t\t\t\t<div class=\"tab-content\" id=\"myTabContent\">\n");
      out.write("\t\t\t\t\t\t\t<!-- Start Single Tab -->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tab-pane fade show active\" id=\"man\" role=\"tabpanel\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tab-single\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-xl-3 col-lg-4 col-md-4 col-12\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"single-product\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"product-img\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"product-details.html\"> <img\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"default-img\" src=\"images/book-3.png\" alt=\"#\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"button-head\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"product-action-2\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a title=\"Add to cart\" href=\"#\">Add to cart</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<!--/ End Single Tab -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-primary btn-lg\"\n");
      out.write("\t\t\tstyle=\"margin: 40px auto; display: flex;\">Load More</button>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- End Comic Latest -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.jsp", out, false);
      out.write("\n");
      out.write("\t<script\n");
      out.write("\t\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("\t<script>\n");
      out.write("\t\tfunction loadMore() {\n");
      out.write("\t\t\tvar amount = document.getElementsByClassName(\"product\").length;\n");
      out.write("\t\t\t$.ajax({\n");
      out.write("\t\t\t\turl : \"/WebsiteBookStore/load\",\n");
      out.write("\t\t\t\ttype : \"get\", //send it through get method\n");
      out.write("\t\t\t\tdata : {\n");
      out.write("\t\t\t\t\texits : amount\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\tsuccess : function(data) {\n");
      out.write("\t\t\t\t\tvar row = document.getElementById(\"content\");\n");
      out.write("\t\t\t\t\trow.innerHTML += data;\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\terror : function(xhr) {\n");
      out.write("\t\t\t\t\t//Do Something to handle error\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t}\n");
      out.write("\t\tfunction loadMoreNovel() {\n");
      out.write("\t\t\tvar amountNovel\t = document.getElementsByClassName(\"productNovel\").length;\n");
      out.write("\t\t\t$\n");
      out.write("\t\t\t\t\t.ajax({\n");
      out.write("\t\t\t\t\t\turl : \"/WebsiteBookStore/loadNovel\",\n");
      out.write("\t\t\t\t\t\ttype : \"get\", //send it through get method\n");
      out.write("\t\t\t\t\t\tdata : {\n");
      out.write("\t\t\t\t\t\t\texitsNovel : amountNovel\n");
      out.write("\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\tsuccess : function(dataNovel) {\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"contentNovel\").innerHTML += dataNovel;\n");
      out.write("\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\terror : function(xhr) {\n");
      out.write("\t\t\t\t\t\t\t//Do Something to handle error\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t});\n");
      out.write("\t\t}\n");
      out.write("\t\tfunction loadMoreAdidas() {\n");
      out.write("\t\t\tvar amountAdidas = document.getElementsByClassName(\"productAdidas\").length;\n");
      out.write("\t\t\t$\n");
      out.write("\t\t\t\t\t.ajax({\n");
      out.write("\t\t\t\t\t\turl : \"/WebsiteBookStore/loadAdidas\",\n");
      out.write("\t\t\t\t\t\ttype : \"get\", //send it through get method\n");
      out.write("\t\t\t\t\t\tdata : {\n");
      out.write("\t\t\t\t\t\t\texitsAdidas : amountAdidas\n");
      out.write("\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\tsuccess : function(dataAdidas) {\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"contentAdidas\").innerHTML += dataAdidas;\n");
      out.write("\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\terror : function(xhr) {\n");
      out.write("\t\t\t\t\t\t\t//Do Something to handle error\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t});\n");
      out.write("\t\t}\n");
      out.write("\t\tfunction searchByName(param) {\n");
      out.write("\t\t\tvar txtSearch = param.value;\n");
      out.write("\t\t\t$.ajax({\n");
      out.write("\t\t\t\turl : \"/WebsiteBookStore/searchAjax\",\n");
      out.write("\t\t\t\ttype : \"get\", //send it through get method\n");
      out.write("\t\t\t\tdata : {\n");
      out.write("\t\t\t\t\ttxt : txtSearch\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\tsuccess : function(data) {\n");
      out.write("\t\t\t\t\tvar row = document.getElementById(\"content\");\n");
      out.write("\t\t\t\t\trow.innerHTML = data;\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\terror : function(xhr) {\n");
      out.write("\t\t\t\t\t//Do Something to handle error\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t}\n");
      out.write("\t\tfunction load(cateid) {\n");
      out.write("\t\t\t$\n");
      out.write("\t\t\t\t\t.ajax({\n");
      out.write("\t\t\t\t\t\turl : \"/WebsiteBookStore/category\",\n");
      out.write("\t\t\t\t\t\ttype : \"get\", //send it through get method\n");
      out.write("\t\t\t\t\t\tdata : {\n");
      out.write("\t\t\t\t\t\t\tcid : cateid\n");
      out.write("\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\tsuccess : function(responseData) {\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"content\").innerHTML = responseData;\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t});\n");
      out.write("\t\t}\n");
      out.write("\t\tfunction loadAmountCart() {\n");
      out.write("\t\t\t$\n");
      out.write("\t\t\t\t\t.ajax({\n");
      out.write("\t\t\t\t\t\turl : \"/WebsiteBookStore/loadAllAmountCart\",\n");
      out.write("\t\t\t\t\t\ttype : \"get\", //send it through get method\n");
      out.write("\t\t\t\t\t\tdata : {\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\tsuccess : function(responseData) {\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"amountCart\").innerHTML = responseData;\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t});\n");
      out.write("\t\t}\n");
      out.write("\t</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<!-- Custom scripts -->\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/script.js\"></script>\n");
      out.write("\n");
      out.write("\t<!-- Jquery -->\n");
      out.write("\t<script\n");
      out.write("\t\tsrc=\"https://mdbootstrap.com/previews/ecommerce-demo/js/jquery-3.4.1.min.js\"></script>\n");
      out.write("\t<script src=\"js/jquery.min.js\"></script>\n");
      out.write("\t<script src=\"js/jquery-migrate-3.0.0.js\"></script>\n");
      out.write("\t<script src=\"js/jquery-ui.min.js\"></script>\n");
      out.write("\t<!-- Popper JS -->\n");
      out.write("\t<script src=\"js/popper.min.js\"></script>\n");
      out.write("\t<!-- Bootstrap JS -->\n");
      out.write("\t<script src=\"js/bootstrap.min.js\"></script>\n");
      out.write("\t<!-- Color JS -->\n");
      out.write("\t<script src=\"js/colors.js\"></script>\n");
      out.write("\t<!-- Slicknav JS -->\n");
      out.write("\t<script src=\"js/slicknav.min.js\"></script>\n");
      out.write("\t<!-- Owl Carousel JS -->\n");
      out.write("\t<script src=\"js/owl-carousel.js\"></script>\n");
      out.write("\t<!-- Magnific Popup JS -->\n");
      out.write("\t<script src=\"js/magnific-popup.js\"></script>\n");
      out.write("\t<!-- Waypoints JS -->\n");
      out.write("\t<script src=\"js/waypoints.min.js\"></script>\n");
      out.write("\t<!-- Countdown JS -->\n");
      out.write("\t<script src=\"js/finalcountdown.min.js\"></script>\n");
      out.write("\t<!-- Nice Select JS -->\n");
      out.write("\t<script src=\"js/nicesellect.js\"></script>\n");
      out.write("\t<!-- Flex Slider JS -->\n");
      out.write("\t<script src=\"js/flex-slider.js\"></script>\n");
      out.write("\t<!-- ScrollUp JS -->\n");
      out.write("\t<script src=\"js/scrollup.js\"></script>\n");
      out.write("\t<!-- Onepage Nav JS -->\n");
      out.write("\t<script src=\"js/onepage-nav.min.js\"></script>\n");
      out.write("\t<!-- Easing JS -->\n");
      out.write("\t<script src=\"js/easing.js\"></script>\n");
      out.write("\t<!-- Active JS -->\n");
      out.write("\t<script src=\"js/active.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /Home.jsp(61,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/Home.jsp(61,6) '${list8Last}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list8Last}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /Home.jsp(61,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("o");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("\t\t\t\t\t\t\t<!-- Start Single Product -->\n");
            out.write("\t\t\t\t\t\t\t<div class=\"single-product\">\n");
            out.write("\t\t\t\t\t\t\t\t<div class=\"product-img\">\n");
            out.write("\t\t\t\t\t\t\t\t\t<a href=\"detail?pid=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"> <img class=\"default-img\"\n");
            out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" alt=\"#\"> <span class=\"out-of-stock\">New</span>\n");
            out.write("\t\t\t\t\t\t\t\t\t</a>\n");
            out.write("\t\t\t\t\t\t\t\t\t<div class=\"button-head\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product-action-2\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<a title=\"Add to cart\" href=\"#\">Add to cart</a>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t<div class=\"product-content\">\n");
            out.write("\t\t\t\t\t\t\t\t\t<h3>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"detail?pid=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a>\n");
            out.write("\t\t\t\t\t\t\t\t\t</h3>\n");
            out.write("\t\t\t\t\t\t\t\t\t<div class=\"product-price\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"old\"></span> <span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\n");
            out.write("\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t<!-- End Single Product -->\n");
            out.write("\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /Home.jsp(111,10) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/Home.jsp(111,10) '${list4NovelLast}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list4NovelLast}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /Home.jsp(111,10) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("o");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"productNovel col-xl-3 col-lg-4 col-md-4 col-12\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"single-product\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"product-img\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"detail?pid=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"> <img class=\"default-img\"\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" alt=\"#\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</a>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"button-head\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"product-action-2\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a title=\"Add to cart\" href=\"#\">Add to cart</a>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"text-align: center; font-size: 14px; font-weight: 500; padding: 4px\"\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"novel\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
