/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2022-11-15 13:15:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/F:/Java/java-workspaces/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WebsiteBookStore/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1668259456904L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Header -->\n");
      out.write("<header class=\"header shop\">\n");
      out.write("\t<!-- Topbar -->\n");
      out.write("\t<div class=\"topbar\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 col-md-12 col-12\">\n");
      out.write("\t\t\t\t\t<!-- Top Left -->\n");
      out.write("\t\t\t\t\t<div class=\"top-left\">\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-main\">\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"ti-headphone-alt\"></i> +0123 456 789</li>\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"ti-email\"></i> ebookstore.final@gmail.com</li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!--/ End Top Left -->\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-lg-8 col-md-12 col-12\">\n");
      out.write("\t\t\t\t\t<!-- Top Right -->\n");
      out.write("\t\t\t\t\t<div class=\"right-content\">\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-main\">\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"ti-location-pin\"></i> Store location</li>\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"ti-alarm-clock\"></i> <a href=\"#\">Daily\n");
      out.write("\t\t\t\t\t\t\t\t\tdeal</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"ti-user\"></i> <a href=\"#\">My account</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"ti-power-off\"></i><a href=\"login.html#\">Login</a></li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- End Top Right -->\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- End Topbar -->\n");
      out.write("\t<div class=\"middle-inner\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-lg-2 col-md-2 col-12\">\n");
      out.write("\t\t\t\t\t<!-- Logo -->\n");
      out.write("\t\t\t\t\t<div class=\"logo\">\n");
      out.write("\t\t\t\t\t\t<a href=\"index.html\"><img src=\"images/logo.png\" alt=\"logo\"></a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!--/ End Logo -->\n");
      out.write("\t\t\t\t\t<!-- Search Form -->\n");
      out.write("\t\t\t\t\t<div class=\"search-top\">\n");
      out.write("\t\t\t\t\t\t<div class=\"top-search\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#0\"><i class=\"ti-search\"></i></a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<!-- Search Form -->\n");
      out.write("\t\t\t\t\t\t<div class=\"search-top\">\n");
      out.write("\t\t\t\t\t\t\t<form class=\"search-form\">\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"Search here...\" name=\"search\">\n");
      out.write("\t\t\t\t\t\t\t\t<button value=\"search\" type=\"submit\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"ti-search\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<!--/ End Search Form -->\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!--/ End Search Form -->\n");
      out.write("\t\t\t\t\t<div class=\"mobile-nav\"></div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-lg-8 col-md-7 col-12\"></div>\n");
      out.write("\t\t\t\t<div class=\"col-lg-2 col-md-3 col-12\">\n");
      out.write("\t\t\t\t\t<div class=\"right-bar\">\n");
      out.write("\t\t\t\t\t\t<!-- Search Form -->\n");
      out.write("\t\t\t\t\t\t<div class=\"sinlge-bar shopping\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"single-icon\"><i class=\"ti-bag\"></i> <span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"total-count\">2</span></a>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- Header Inner -->\n");
      out.write("\t<div class=\"header-inner\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"cat-nav-head\">\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-3\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-9 col-12\">\n");
      out.write("\t\t\t\t\t\t<div class=\"menu-area\">\n");
      out.write("\t\t\t\t\t\t\t<!-- Main Menu -->\n");
      out.write("\t\t\t\t\t\t\t<nav class=\"navbar navbar-expand-lg\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"navbar-collapse\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"nav-inner\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"nav main-menu menu navbar-nav\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li class=\"active\"><a href=\"#\">Home</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Shop</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#newbooks\">New Book</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#service\">Service</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"contact.html\">Contact Us</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</nav>\n");
      out.write("\t\t\t\t\t\t\t<!--/ End Main Menu -->\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<!--/ End Header Inner -->\n");
      out.write("</header>\n");
      out.write("<!--/ End Header -->\n");
      out.write("\n");
      out.write("<!-- Slider Area -->\n");
      out.write("<section class=\"hero-slider\">\n");
      out.write("\t<!-- Single Slider -->\n");
      out.write("\t<div class=\"single-slider\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row no-gutters\">\n");
      out.write("\t\t\t\t<div class=\"col-lg-9 offset-lg-3 col-12\">\n");
      out.write("\t\t\t\t\t<div class=\"text-inner\">\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-lg-7 col-12\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"hero-text\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<h1>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span>UP TO 50% OFF </span>EBook Store\n");
      out.write("\t\t\t\t\t\t\t\t\t</h1>\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Good books, like good friends, are few and chosen; the\n");
      out.write("\t\t\t\t\t\t\t\t\t\tmore select, the more enjoyable.</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"button\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn\">Shop Now!</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<!--/ End Single Slider -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
